# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a GitHub project page then use these settings:
url: "https://mj-tracks.github.io/vocal-track/"
baseurl: "/vocal-track"

# Theme par defaut
theme: plastedre

# Of course don't forget to change the username and projectname to YOUR username and project

# Blog Title
title: "The Vocal Track"

# Blog Description
description: "All Acapella tracks of Michael Jackson's songs"

show_downloads: false

lang: "fr-FR"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/logo.png"

# All tag for posts
tags: [maxi-single isolated multitrack stream filtered]


markdown: kramdown
#highlighter: rouge

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile


plugins:
  - jekyll-seo-tag

