

theme: jekyll-theme-midnight

# Blog Title
title: [The Vocal Track]

# Blog Description
description: [All Acapella tracks of Michael Jackson's songs]

# All tag for posts
tags: [maxi-single isolated multitrack stream filtered]

show_downloads: ["false"]
#google_analytics: [Your Google Analytics tracking ID]

